payega-2mamad1reza/APP1/urls.py
from django.urls import path
from .views import MaghaleView , Addmaghale , MaghaleDetails ,About ,search , PostLike , PostunLike


urlpatterns = [
    path('',MaghaleView.as_view(), name = 'home'),
    path('maghale/<pk>',MaghaleDetails.as_view(), name = 'details'),
    path('additem',Addmaghale , name = 'addMaghale'),
    path('aboutus/',About.as_view(), name = 'aboutus'),
    path('search/',search, name = 'search'),
    path('like/<id>',PostLike, name = 'postlike'),
    path('unlike/<id>',PostunLike, name = 'postunlike'),
]

payega-2mamad1reza/accounts/urls.py
from django.urls import path
from .views import SignUp , Login  , Logout

app_name = 'accounts'
urlpatterns = [
    path('signup/',SignUp, name = 'signup'),
    path('login/',Login, name = 'login'),
    path('logout/',Logout, name = 'logout'),
]

payega-2mamad1reza/mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('APP1.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payega-2mamad1reza/APP1/models.py
from django.db import models
from django.contrib.auth.models import User


class AddressUny(models.Model):

    address1 = models.CharField("Address line 1", max_length=1024)

    zip_code = models.CharField("ZIP / Postal code", max_length=12)

    city = models.CharField("City", max_length=1024,)

    st = models.CharField("street", max_length=20)


class University(models.Model):
    Name = models.CharField(max_length=100)
    Phone = models.CharField(max_length=20)
    addres = models.ForeignKey(AddressUny, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.Name


class Professor(models.Model):
    Email_p = models.EmailField()
    Degree_of_education_p = models.ImageField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    uni = models.ForeignKey(University, on_delete=models.CASCADE, null=True, blank=True)
    name_p = models.CharField(max_length=50, null=True, blank=True)
    family_p = models.CharField(max_length=50, null=True, blank=True)
    age_p = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name_p


class Student(models.Model):
    Email_s = models.EmailField()
    degree_of_education_p = models.FileField(upload_to='media/', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    teacher = models.ForeignKey(Professor, on_delete=models.CASCADE, null=True, blank=True)
    number_of_student = models.IntegerField(null=True, blank=True, unique=True)
    uni = models.ForeignKey(University, on_delete=models.CASCADE, null=True, blank=True)
    name_s = models.CharField(max_length=50, null=True, blank=True)
    family_s = models.CharField(max_length=50, null=True, blank=True)
    age_s = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name_s


class Maghale(models.Model):
    Code_Maghale = models.IntegerField()
    title_Maghale = models.CharField(max_length=200)
    Grouping_Maghale = models.CharField(max_length=200)
    Professor_Maghale = models.ForeignKey(Professor, on_delete=models.CASCADE, null=True, blank=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True, blank=True)
    file = models.FileField(upload_to='media/', null=True, blank=True)
    like = models.ManyToManyField(User, related_name='Blogliks', blank=True)
    ShortExplanation = models.TextField(null=True, blank=True)
    choise = [
        ('like', 'like'),
        ('dislike', 'dislike'),
    ]
    vaziat = models.CharField(max_length=20, choices=choise, null=True)

    def __str__(self):
        return self.title_Maghale
    
    def getsnippet(self):
        return self.ShortExplanation[0:100] + '...'    

class AboutUs(models.Model):
    title_A = models.CharField(max_length=100, null=True, blank=True)
    conrext_A = models.CharField(max_length=1000, null=True, blank=True)

payega-2mamad1reza/APP1/forms.py
from django import forms


class AddmaghaleForm(forms.Form):
    title_Maghale = forms.CharField( label ='Title',max_length = 200 )
    Code_Maghale = forms.IntegerField ( label='Article Code')
    Grouping_Maghale = forms.CharField( label ='Article Type',max_length = 50 )
    file = forms.FileField( label='File')
    ShortExplanation = forms.CharField(label='ShortExplanation', widget=forms.Textarea)
    number_of_Student = forms.IntegerField(label='Student Number')
    name_s = forms.CharField( label ='Student Name',max_length = 50 )
    name_p = forms.CharField( label ='Professor Name',max_length = 50 )

payega-2mamad1reza/APP1/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import Maghale, Professor, AboutUs, Student
from .forms import AddmaghaleForm
from django.http import HttpResponse


class MaghaleView(generic.ListView):
    template_name = 'APP1/home.html'
    context_object_name = 'maghalelist'

    def get_queryset(self):
        return Maghale.objects.raw('select * from APP1_maghale')


class MaghaleDetails(generic.DetailView):
    model = Maghale
    template_name = 'APP1/Details.html'


class About(generic.ListView):
    template_name = 'APP1/AboutUs.html'
    context_object_name = 'aboutUs'

    def get_queryset(self):
        return AboutUs.objects.raw('select * from APP1_aboutus')


def Addmaghale(request):
    if request.method == "POST":
        form = AddmaghaleForm(request.POST, request.FILES)
        if form.is_valid():
            name_s = form.cleaned_data['name_s']
            name_p = form.cleaned_data['name_p']
            number_of_Student = form.cleaned_data['number_of_Student']
            title_Maghale = form.cleaned_data['title_Maghale']
            Code_Maghale = form.cleaned_data['Code_Maghale']
            Grouping_Maghale = form.cleaned_data['Grouping_Maghale']
            file = form.cleaned_data['file']
            ShortExplanation = form.cleaned_data['ShortExplanation']
            prof = Professor.objects.raw('select * from APP1_professor where name_p = %s', [name_p])
            proff = prof[0]
            student = Student.objects.get(number_of_student=number_of_Student)
            
            maghale = Maghale.objects.create(Code_Maghale=Code_Maghale, title_Maghale=title_Maghale,ShortExplanation=ShortExplanation,
                                             Grouping_Maghale=Grouping_Maghale, Professor_Maghale=proff, student=student, file=file)

            maghale.save()
            return HttpResponse('maghale created')

    else:
        form = AddmaghaleForm()
        blog = Maghale.objects.raw('select * from APP1_maghale')

    context = {'form': form}
    return render(request, 'APP1/addMaghale.html', context)


def search(request):
    maghale = Maghale.objects.all()
    if request.method == 'POST':
        title = request.POST['etitle']
        student = request.POST['estudent']
        professor = request.POST['eprofessor']

        try:
            professoremp = Professor.objects.raw('select * from APP1_professor where name_p = %s', [professor])[0]
        except:
            professoremp = None
        try:
            studentemp = Student.objects.raw('select * from APP1_student where name_s = %s', [student])[0]
        except:
            studentemp = None
        if  True:      
            if (title and not student and not professor):
                maghale = Maghale.objects.raw('select * from APP1_maghale where title_Maghale = %s', [title])
            elif(student and not title and not professor and studentemp):
                maghale = Maghale.objects.raw('select * from APP1_maghale where student_id = %s', [studentemp.id])
 
            elif(professor and not title and not student and professoremp):
                maghale = Maghale.objects.raw('select * from APP1_maghale where Professor_Maghale_id = %s', [professoremp.id])

            elif(student and professor and not title and professoremp and studentemp):
                maghale = Maghale.objects.raw('select * from APP1_maghale where student_id = %s and Professor_Maghale_id = %s', [studentemp.id, professoremp.id])

            elif(student and title and not professor and studentemp ):
                maghale = Maghale.objects.raw('select * from APP1_maghale where student_id = %s and title_Maghale = %s', [studentemp.id, title])

            elif(title and professor and not student and professoremp):
                maghale = Maghale.objects.raw('select * from APP1_maghale where title_Maghale = %s and Professor_Maghale_id = %s', [title, professoremp.id])
            elif(studentemp and professoremp and title ):
                maghale = Maghale.objects.raw(
                    'select * from APP1_maghale where student_id = %s and Professor_Maghale_id = %s and title_Maghale = %s', [studentemp.id, professoremp.id, title])
            context = {
                'maghale': maghale
            }
            return render(request, 'APP1/search.html', context)
    return render(request, 'APP1/search.html')


def PostLike(request, id):
    post = Maghale.objects.raw(f'SELECT * FROM APP1_maghale WHERE id = {id}')[0]
    user = request.user
    try:
        puser = Professor.objects.get(user=user)
        if (post.Professor_Maghale == puser):
            if puser.user.is_authenticated:

                if puser.user in post.like.all():
                    return HttpResponse('you like this post already')
                else:

                    post.like.add(puser.user)
                    post.vaziat = 'like'
                    post.save()
                    return redirect('details', id)
            else:
                return HttpResponse('you not allow like this post')
        else:
            return HttpResponse("you are not this article professor ")
    except:
        return HttpResponse("you are not professor")


def PostunLike(request, id):
    post = Maghale.objects.raw(f'SELECT * FROM APP1_maghale WHERE id = {id}')[0]
    user = request.user
    try:
        puser = Professor.objects.get(user=user)

        if puser.user.is_authenticated:

            if puser.user in post.like.all():
                post.like.remove(puser.user)
                post.vaziat = 'dislike'
                post.save()
                return redirect('details', id)
            else:
                return HttpResponse('you not like this post')
        else:
            return HttpResponse('you not allow like this post')

    except:
        return HttpResponse("you are not professor")

payega-2mamad1reza/APP1/templates/APP1/AboutUs.html
{% extends 'base.html' %}

{% block title %} AboutUs {% endblock title %}
{% block content %}
<div class=" a owerflow-hiden" style="height: 100vh;">
    <div class=" col-sm-12 ">
        <h1 class=" py-4 bg-primary text-black-50 my-4 text-center">:سیتم اطلاعاتی ثبت و تایید مقالات علمی و تخصصی 
        </h1>
        <p class=" text-justify text-right text-Aboutus-color">
            با توجه به نیاز های جامعه علمی اعم از نبودن ت مقالات دانشجویان و
            پژوهشگران تصمیم گرفتیم سیستمی طراحی کنیم که نیاز ها جامعه علمی را برطرف کرده و در آن افراد
            بتوانند به ثبت مقاله یا در صورت نیاز ازمقاله دیگر کاربران استفاده نمایند. ما برای طراحی این سیستم از
            ذی نفعان آن برای ارائه هرجه به یی خدمات ،خواسته های آنها را پرس و جوکرده و به نتای یج رسیده
            ایم،از جمله:سیستم اطلاعا یت مربوطه باید دارای امنیت وکیفیت باشد به معنای اینکه هر شخص در
            فضای شخصی خودش بتواند فعالیت مربوطه را انجام داده و به اطلاعات دیگر افراد دس ییسی نداشته
            باشد.همچن ر یی دارای فضایت برای مدیر سیستم که میخواهند مقالات را تاییدکند باشداین سیستم
            ی
            از جمله اطلاعات کاربر(دانشجو یا پژوهشگر) مانند اطلاعات حقی یق و همچن ری
            یت
            ها
            اطلاعا یت داده
            نشر
            اطلاعات مقالات مانند موضوع مقاله تاری خ مقاله و همچن ر یی مالک آن را در خود ذخ ریه میکندکه
            تی
            عا
            این سیستم اطلا موجب کمک به افراد برای سرعت بخشیدن به کار هایشان میشود.
        </p>
    </div>
</div>


{% endblock content %}

payega-2mamad1reza/APP1/templates/APP1/Details.html
{% extends 'base.html' %}

{% block title %} Details {% endblock title %}

    

    {% block content %}
    <div class="a" style="height: 100vh;">
    <div class="row container mx-auto card bg-card-details pt-3 ">
        <h1 class="text-black font-weight-bold mx-auto pb-3">{{maghale.title_Maghale}}</h1>
        <table class="table">
            <thead>
              <tr>
                <th scope="col"><h5 class=" font-weight-bold text-center">Article Code</h5></th>
                <th scope="col"><h5 class=" font-weight-bold text-center">Article Type</h5></th>
                <th scope="col"><h5 class=" font-weight-bold text-center">Superviser</h5></th>
                <th scope="col"><h5 class=" font-weight-bold text-center">Student Name</h5></th>
                <th scope="col"><h5 class=" font-weight-bold text-center">Status</h5></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class=" font-weight-bold text-center">{{maghale.Code_Maghale}}</th>
                <td class=" font-weight-bold text-center">{{maghale.Grouping_Maghale}}</td>
                <td class=" font-weight-bold text-center">{{maghale.Professor_Maghale}}</td>
                <td class=" font-weight-bold text-center">{{maghale.student}}</td>
                <td class=" font-weight-bold text-center">{{maghale.vaziat}}</td>
              </tr>
              
            </tbody>
          </table>
        <div class=" row container mx-auto justify-content-center card-footer"> 
            <a class="btn btn-primary  " href="{{ maghale.file.url }}" > Download PDF </a>
        </div>
    </div>
    <div class=" container row mx-auto justify-content-center my-3">
        {% if user in maghale.like.all %}
        <a href="{% url 'postunlike' maghale.id %}" class="btn btn-danger">unlike</a>
        {% else %}
        <a href="{% url 'postlike' maghale.id %}" class="btn btn-success">like</a>
        {% endif %}
    </div>
</div> 
    {% endblock content %}

    

      <!-- <div class=" col-12 text-center ">
        
        <p class=" font-weight-bold text-black">
        Code_Maghale_is: {{maghale.Code_Maghale}}
        </p>
        <p class=" font-weight-bold text-black">
        Grouping_Maghale_is: {{maghale.Grouping_Maghale}}
        </p>
        <p class=" font-weight-bold text-black">
            Professor_Maghale_is: {{maghale.Professor_Maghale}}
        </p>
        <p class=" font-weight-bold text-black">
            student_is: {{maghale.student}}
        </p>
        
    
    </div> -->

payega-2mamad1reza/APP1/templates/APP1/addMaghale.html
{% extends 'base.html' %}

{% block title %} AddMaghale {% endblock title %}

{% block content %}
<div class="a row text-center justify-content-center mx-auto font-weight-bold " style="height: 150vh;">
<form enctype="multipart/form-data" action = " {% url 'addMaghale' %} " method = "POST" class=" col-2 mx-auto color-text-addM mt-5">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn   my-3 mx-3 btn-addM">SEND</button>
</form>
</div>
{% endblock content %}

    

payega-2mamad1reza/APP1/templates/APP1/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock title %}

{% block content %}

<div class="a owerflow-hiden" style="height: 100vh;">
    {% if user.is_authenticated %}
    <h5 class=" text-center text-light"> Username: {{ user.username }}</h5>
    
    {% endif %}
    <div class="container-fluid row justify-content-center k mt-5">
        {% for post in maghalelist %}
        <div class="card col-auto text-center b m-1 rounded-20" style="width: 18rem;">
            <div class="card-body">
            <h5 class="card-title font-weight-bold font-italic">{{ post.title_Maghale }}</h5>
            <h6 class="card-subtitle mb-2 color-text">{{post.Grouping_Maghale}}</h6>
            <h6 class="card-subtitle mb-2 color-text">{{post.Code_Maghale}}</h6>
            <p class="card-text">{{post.getsnippet}}</p>
            <a href="{% url 'details' post.id %}" class="card-link color-link font-weight-bold">Go somewhere</a>
            </div>
            
        </div> 
        {% endfor %}
        
    </div>
    {% if user.is_authenticated %}
    <div class=" row justify-content-center py-4">
        <a href="additem" class="btn btn-info btn-add-m"> Add Article  </a>
    </div>
    {% endif %} 
    <div class="container row justify-content-center mx-auto k">
        <div class=" col-auto">
            {% if user.is_authenticated %}
        <form action="{% url 'accounts:logout' %}" method="" class="py-3">
            {% csrf_token %}
            <button type="submit" class=" btn btn-info btn-logout px-5 py-3"> Logout</button>
        </form>
        {% else %}
        <form action="{% url 'accounts:login' %}" method="" class="py-3">
            {% csrf_token %}
            <button type="submit" class=" btn btn-primary btn-login px-5 py-3"> Login</button>
        </form>
        
        {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

payega-2mamad1reza/APP1/templates/APP1/search.html
{% extends 'base.html' %}

{% block title %} Search {% endblock title %}

{% block content %}
    <div class="container-fluid row mx-auto justify-content-center a text-warning font-weight-bold" style="height: 150vh;">
        <div class="mt-5">
            <form method="POST" class="post-form py-4" action="/search/" id="editform">
                
                {% csrf_token %}
                <div class="row">
                    <label for="nameid" class="col-6 color-text-search">Search By Title  : </label>
                    <input type="text" id="nameid" value="" name="etitle" class="col-6"> 
                </div>
                
                
                <br>
                <div class="row">
                    <label for="nameid" class="col-6 color-text-search">Search By Student : </label>
                    <input type="text" id="nameid" value="" name="estudent" class="col-6"> 
                </div>
                
                <br>
                <div class="row">
                <label for="quantity" class="col-6 color-text-search">Search By Professor :</label>
                <input type="text" id="quantity" name="eprofessor"class="col-6">
                </div>
                <br>
                <input type="submit" value="search" class="btn btn-success btn-block">
                <br>
                <div class=" container-fluid row justify-content-center mx-auto">
                {% for magh in maghale %}
                
                <div class="card col-auto text-center b m-1" style="width: 18rem;">
                    <div class="card-body">
                    <h5 class="card-title font-weight-bold font-italic color-text-search-card">{{ magh.title_Maghale }}</h5>
                    <h6 class="card-subtitle mb-2 color-text">{{magh.Grouping_Maghale}}</h6>
                    <h6 class="card-subtitle mb-2 color-text">{{magh.Code_Maghale}}</h6>
                    <p class="card-text">{{magh.getsnippet}}</p>                    
                    <a href="{% url 'details' magh.id %}" class="card-link color-link">Go somewhere</a>
                    </div>
                
                </div> 

            
                {% endfor %}
            </div>
            </form>
        </div>
    </div>
        
    
{% endblock content %}

{{magh.title_Maghale}}